---
title: "ML_hw7"
author: "박지은"
date: '2020 4 19 '
output: html_document
---
## 1번
```{r}
states = as.data.frame(state.x77)
colnames(states)

# 1-1
fit = lm(Murder~., data=states)
fit2 = step(fit, direction="both")
fit2

# 1-2
# Population, Illiteracy, Life Exp, Frost, Area

# 1-3
# population이 한 단위 증가할 때 Murder가 1.780e-04배 증가한다.
# Area가 한 단위 증가할 때 Murder가 6.804e-06배 증가한다.
```

## 2번
```{r}
# 2-1
setwd('C:/Users/danan/Desktop/Bitamin/ML_R/reviews')
ex1 = read.csv('사례연구3.csv',header=T)
str(ex1)
colnames(ex1)[1] = "subject"
ex1$subject = factor(ex1$subject)
ex1$age = factor(ex1$age)
ex1$teaching = factor(ex1$teaching)
levels(ex1$teaching)

library(nnet)
ex1.multi = multinom(teaching~.,data=ex1)
ex1.sum = summary(ex1.multi)
ex1.sum
round(exp(ex1.sum$coefficients),3)
# 2-2
# science : science를 선택한 사람은 arts를 선택한 사람에 비해 lecture를 선택할 확률이 0.057배이다.
# age11 : age11인 사람은 10살인 사람에 비해 lecture를 선택할 확률이 1.82배 높다.
# age13 : age13인 사람은 10살인 사람에 비해 lecture를 선택할 확률이 0.559배이다.
# y = 0일때 discuss이고, y=1일때 lecture!!!

# 2-3
# F / 근거: 비교대상의 기준이 되는 Reference이기 때문이다.
```

## 3번
```{r}
library(foreign)
library(nnet)
library(ggplot2)
library(reshape2)
m1 = read.dta("https://stats.idre.ucla.edu/stat/data/hsbdemo.dta")
with(m1, table(ses,prog))
with(m1, do.call(rbind,tapply(write, prog, function(x) c(M=mean(x), SD= sd(x)))))

# 3-1
str(m1)
levels(m1$prog)
m1$prog2=relevel(m1$prog, ref="academic")
levels(m1$prog2)
m1.multi = multinom(prog2~ses+write,data=m1)
m1.sum = summary(m1.multi)
m1.sum

z = m1.sum$coefficients/m1.sum$standard.errors
p_value = round((1-pnorm(abs(z), 0, 1))*2,3)
p_value

# 3-2
round(exp(m1.sum$coefficients),3)
# SES가 middle인 학생들이 low인 학생들보다 academic이 아닌 vocation을 선택할 odds가 약 1.3배 높았다.
# SES가 middle인 학생들이 low인 학생들보다 academic이 아닌 general을 선택할 odds가 약 0.5배 높았다.
# SES가 high인 학생들이 low인 학생들보다 academic이 아닌 general을 선택할 odds가 약 0.3배 높았다.
# SES가 high인 학생들이 low인 학생들보다 academic이 아닌 vocation을 선택할 odds가 약 0.3배 높았다.
# write가 한단위 증가할 때 academic 아닌 general 택할 확률 약 0.94배이다.
# write가 한단위 증가할 때 academic 아닌 vocation 택할 확률 약 0.89배이다.
```
